### ISSUE TITLE
[bug] distracted users don see messages and laerts from roundcube

### ISSUE THREAD

**Issue by mckaygerhard** [texxasrulez/Roundcube_Skins#5]
alert and messages in classic skin its in the middle of the screen so user "must" have to see it.. 

in larrry based are at the corner so if user are distracted dont see it!

please how can i configure this or move it to more in the center for this skins?

**Comment by texxasrulez** [comment]
This is not a bug. Only advise for you is to fork to your own project and dig deep into the code and find out where this part of code is located and make it how you would like.

**Comment by mckaygerhard** [comment]
any tip where are the css clases that moved the messge to the center of the screen and enhanche the fonts?

**Comment by texxasrulez** [comment]
Honestly I am swamped at the moment building an ecommerce site for my company. I do not remember right off the top off my head but I do believe it is located within the jqueryui portion of the themes. I wished I had more time and I would take a refresher look at it. It has been a while since I did anything with this. If you haven't figured it out by the time I get a little time, I will look at that and let you know. Just give me a few months at the least. I do thank you

**Comment by mckaygerhard** [comment]
thanks in advance, i searching too that portion of code.. in geany of course  U_U
