### ISSUE TITLE
plain behaviour, no gradients and roundless versions/flavours

### ISSUE THREAD

**Issue by mckaygerhard** [texxasrulez/Roundcube_Skins#6]
today larry skin are more plain and less rounded.. 

can be more like that for more eye candy and less heavy to browsers?

**Comment by mckaygerhard** [comment]
also no gradient !

keep the good work

( made my own versions but i put a issue request just to know)

**Comment by texxasrulez** [comment]
I did these like old school larry because that it what I like. For years I looked for other themes, and while there are some nice ones, not EXACTLY the look I want and hardly any plugin support, so I wrote my own according to my particular tastes and then shared it with the world. I do plan on making more colors, but no plans on flattening out colors, just not my cup of tea.

 I am closing this as an issue as it is more a request. Thanks for your input.

P.S.
You mentioned making your own. Are those available for download? I would be keen on checking out your work. Thanx again

**Comment by mckaygerhard** [comment]
> You mentioned making your own. Are those available for download? I would be keen on checking out your work. 

well i discovered are not so easy as erase the "gradient" lines.. KAKAKAK

the look and fiel need more work.. so as you said.. seems ist better let it as is

> I do plan on making more colors, but no plans on flattening out colors, just not my cup of tea.

i understand.. was just a feature request issue..

**Comment by mckaygerhard** [comment]
> You mentioned making your own. Are those available for download? I would be keen on checking out your work.
 
hi, i started to retrieve some skins in web and refrested in https://github.com/roundcubevnz, now i learned a little and try to deploy in that group.. wil be slowly but i will try
